### ISSUE TITLE
Update README to explain that this is actually a fork

### ISSUE THREAD

**Issue by brunetton** [lrq3000/hexiano#4]
Hi @lrq3000 

First of all, THANKS a lot for this ! This fork solved for me the problem of repeating keys that doesn't works.

It took me some time to understand that this project is actually a fork of the original Hexiano (I think I'm not wrong). 

As [releases](https://github.com/lrq3000/hexiano/releases) are named "Hexiano Extended", why not updating README.md with this name ? And explain that this isn't deployed on f-droid for now for logo and name copyrights problems, with links to the logo issue ?

Thanks a lot for this ! I'm happy to play open-source Janko keyboard again :star_struck:

**Comment by lrq3000** [comment]
Thank you for your suggestion. The name Hexiano is trademarked by the 2nd author who thought about it, so we cannot really use it.

I will clarify that this is a fork in the README, but this issue will ultimately be solved with the rebranding in #2.
